pages:
  - Home: 'index.md'
  - User Documentation:
    - Getting Started: 'user/getting_started.md'
    - Installation: 'user/installation.md'
    - C++ Style Guide: 'user/c++_style_guide.md'
    - Environment: 'user/environment.md'
  - Server Documentation:
    - Getting started: 'server/getting_started.md'
    - Installation: 'server/installation.md'
    - Orchestration: 'server/orchestration.md'
  - Software Documentation:
    - Overview: 'software/overview.md'
    - Interface RS485: 'software/interface_RS485.md'
    - Provider DVL: 'software/provider_dvl.md'
    - Provider IMU: 'software/provider_imu.md'
    - Provider Sonar: 'software/provider_sonar.md'
    - Provider Media: 'software/provider_media.md'
    - Proc Vision: 'software/proc_vision.md'
    - Proc Navigation: 'software/proc_navigation.md'
  - Electrical Documentation:
    - Overview: 'electrical/overview.md'
    - Hydrophones: 'electrical/hydrophones.md'
    - DVL: 'electrical/dvl.md'
  - Mechanical Documentation:
    - Overview: 'mechanical/overview.md'
  - Proof of Concept:
    - 2018-2019: 'POC/2018_2019.md'
  - About S.O.N.I.A.:
    - The Project: 'about/project.md'
    - Open Source Philosophy: 'about/open_source.md'
    - Sponsors of S.O.N.I.A.: 'about/sponsors.md'

site_name: S.O.N.I.A. Documentation
repo_url: https://github.com/sonia-auv/documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs
